CREATE TABLE log(
    id INT AUTO_INCREMENT PRIMARY KEY,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    phrase VARCHAR(128) NOT NULL,
    letters VARCHAR(32) NOT NULL,
    ip VARCHAR(16) NOT NULL,
    browser_string VARCHAR(256) NOT NULL,
    results VARCHAR(64) NOT NULL
);

